" Downloads and installs the plugin manager if not present
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Configuration for the plugin manager
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()

" Gruvbox theme plugin 
set background=dark
let g:gruvbox_transparent_bg=1
colorscheme gruvbox

" Start Nerdtree only when no filename specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" Vim integrated configuration
syntax on
filetype indent on
set showmode
set showcmd
set encoding=utf-8
set t_Co=256
set autoindent
set expandtab
set number 
set cursorline
set showmatch
set noerrorbells
set relativenumber
set rnu

set hlsearch
set smartcase
set ignorecase
set incsearch

set ruler
 
set undolevels=1000
set backspace=indent,eol,start

